sudo: false
language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libboost-dev
            - libtiff5-dev

before_script: 

script:
   - make
   - ./3dsimTIFF example_data/foo.tif
